\set ON_ERROR_STOP on
\pset pager off
\timing on

-- CHANGING SCRIPT.
-- Run only after reviewing 010_preflight_order_trans.sql output.
-- Does not modify raw_ax.wmsordertrans.

BEGIN;
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '30min';

CREATE SCHEMA IF NOT EXISTS stage_ax;

-- Keep trans_id as the internal sequence-based DDS surrogate key.
-- Store AX RECID separately as bigint.
ALTER TABLE dds.order_trans
    ADD COLUMN IF NOT EXISTS rec_id bigint;

COMMENT ON COLUMN dds.order_trans.trans_id IS
    'Internal DDS surrogate key generated by dds.order_trans_trans_id_seq';

COMMENT ON COLUMN dds.order_trans.rec_id IS
    'AX 2012 WMSORDERTRANS.RECID converted to bigint';

COMMENT ON COLUMN dds.order_trans.order_trans_id IS
    'AX 2012 WMSORDERTRANS.INVENTTRANSID';

-- Required for idempotent INSERT ... ON CONFLICT (rec_id).
-- dds.order_trans is currently empty, so creation should be fast.
CREATE UNIQUE INDEX IF NOT EXISTS ux_order_trans_rec_id
    ON dds.order_trans (rec_id);

-- Staging keeps only fields required for DDS and integrations.
CREATE UNLOGGED TABLE IF NOT EXISTS stage_ax.wmsordertrans_normalized
(
    recid_bigint       bigint      NOT NULL,
    source_recid       text        NOT NULL,
    order_id           text,
    order_trans_id     text,
    item_id            text,
    invent_dim_id      text,
    qty                numeric,
    picked_qty         numeric,
    waste_qty          numeric,
    route_id           text,
    pallet_id          text,
    modified_datetime  timestamp without time zone,
    created_datetime   timestamp without time zone,
    data_area_id       text,
    loaded_at          timestamp with time zone NOT NULL DEFAULT clock_timestamp()
);

-- Empty-table index creation is quick. This enables idempotent chunk retries.
CREATE UNIQUE INDEX IF NOT EXISTS ux_stage_wmsordertrans_recid_bigint
    ON stage_ax.wmsordertrans_normalized (recid_bigint);

CREATE UNIQUE INDEX IF NOT EXISTS ux_stage_wmsordertrans_source_recid
    ON stage_ax.wmsordertrans_normalized (source_recid);

ANALYZE stage_ax.wmsordertrans_normalized;
COMMIT;
