"""HTML load report generator."""

import os
from datetime import datetime
from typing import Optional


def generate_html_report(
    table_name: str,
    run_status: str,
    elapsed: float,
    source_count: int,
    target_count: int,
    chunks_total: int,
    chunks_completed: int,
    failed_chunks: int,
    rows_fetched: int,
    rows_inserted: int,
    rows_conflicted: int,
    workers: int,
    output_dir: str = ".",
    prev_inserted: Optional[int] = None,
    peak_memory_mb: float = 0.0,
) -> str:
    """
    Generate HTML load report.

    Returns:
        Path to generated HTML file
    """
    speed = rows_inserted / elapsed if elapsed > 0 else 0
    hours = int(elapsed // 3600)
    minutes = int((elapsed % 3600) // 60)
    seconds = int(elapsed % 60)
    duration_str = f"{hours:02d}:{minutes:02d}:{seconds:02d}"

    status_color = "#4CAF50" if run_status == "completed" else "#f44336"
    diff_html = ""
    if prev_inserted is not None:
        diff = rows_inserted - prev_inserted
        diff_pct = (diff / prev_inserted * 100) if prev_inserted > 0 else 0
        diff_color = "#4CAF50" if diff >= 0 else "#f44336"
        diff_html = f"""
        <tr><td>Previous inserted</td><td>{prev_inserted:,}</td></tr>
        <tr><td>Difference</td><td style="color:{diff_color}">{diff:+,} ({diff_pct:+.1f}%)</td></tr>
        """

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ETL Load Report — {table_name}</title>
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; margin: 40px; background: #f5f5f5; }}
        .container {{ max-width: 800px; margin: 0 auto; background: white; padding: 30px; border-radius: 8px; box-shadow: 0 2px 8px rgba(0,0,0,0.1); }}
        h1 {{ color: #333; border-bottom: 2px solid #eee; padding-bottom: 10px; }}
        .status {{ display: inline-block; padding: 4px 12px; border-radius: 4px; color: white; font-weight: bold; background: {status_color}; }}
        table {{ width: 100%; border-collapse: collapse; margin: 20px 0; }}
        td, th {{ padding: 10px; text-align: left; border-bottom: 1px solid #eee; }}
        th {{ background: #f8f9fa; font-weight: 600; }}
        .metric {{ font-size: 24px; font-weight: bold; color: #333; }}
        .grid {{ display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 20px; margin: 20px 0; }}
        .card {{ background: #f8f9fa; padding: 15px; border-radius: 6px; text-align: center; }}
        .card .label {{ font-size: 12px; color: #666; text-transform: uppercase; }}
        .footer {{ margin-top: 30px; font-size: 12px; color: #999; text-align: center; }}
    </style>
</head>
<body>
    <div class="container">
        <h1>ETL Load Report</h1>
        <p><strong>Table:</strong> {table_name} &nbsp; <span class="status">{run_status.upper()}</span></p>
        <p><strong>Generated:</strong> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>

        <div class="grid">
            <div class="card">
                <div class="label">Duration</div>
                <div class="metric">{duration_str}</div>
            </div>
            <div class="card">
                <div class="label">Rows Inserted</div>
                <div class="metric">{rows_inserted:,}</div>
            </div>
            <div class="card">
                <div class="label">Speed</div>
                <div class="metric">{speed:,.0f} rows/s</div>
            </div>
        </div>

        <table>
            <tr><th colspan="2">Details</th></tr>
            <tr><td>Source rows</td><td>{source_count:,}</td></tr>
            <tr><td>Target rows</td><td>{target_count:,}</td></tr>
            <tr><td>Rows fetched</td><td>{rows_fetched:,}</td></tr>
            <tr><td>Rows inserted</td><td>{rows_inserted:,}</td></tr>
            <tr><td>Rows conflicted</td><td>{rows_conflicted:,}</td></tr>
            {diff_html}
            <tr><td>Chunks</td><td>{chunks_completed}/{chunks_total} completed</td></tr>
            <tr><td>Failed chunks</td><td>{failed_chunks}</td></tr>
            <tr><td>Workers</td><td>{workers}</td></tr>
            <tr><td>Peak memory</td><td>{peak_memory_mb:.1f} MB</td></tr>
        </table>

        <div class="footer">
            Generated by ParallelLoaderV2 ETL Pipeline
        </div>
    </div>
</body>
</html>"""

    filename = f"load_report_{table_name}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.html"
    filepath = os.path.join(output_dir, filename)
    os.makedirs(output_dir, exist_ok=True)
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(html)

    return filepath
