DROP TABLE IF EXISTS #R

CREATE TABLE #R (RecId bigint)

INSERT INTO #R (RecId)
SELECT T.RecId
FROM LFL_WMSPalletWeightStation T
  LEFT JOIN WMSPALLET P ON P.PARTITION = T.PARTITION AND P.DATAAREAID = T.DATAAREAID AND P.WMSPALLETID = T.WMSPALLETID
WHERE T.PARTITION = 5637144576 AND T.DATAAREAID = 'dat'
  AND T.CREATEDDATETIME < '20250401' AND (P.RECID IS NULL OR P.CREATEDDATETIME > T.CREATEDDATETIME)
OPTION (MAXDOP 8)
-- 7281849

CREATE UNIQUE CLUSTERED INDEX #Ridx ON #R (RecId) WITH (MAXDOP = 8)

DROP TABLE IF EXISTS #F

CREATE TABLE #F (RecId bigint)

WHILE (1 = 1) BEGIN
  INSERT INTO #F (RecId)
  SELECT TOP 100000 RecId
  FROM #R
  ORDER BY RecId
  OPTION (MAXDOP 8)

  IF (@@ROWCOUNT = 0) BREAK

  BEGIN TRAN

  INSERT INTO AX63_WMS_ARCH.dbo.LFL_WMSPalletWeightStation (
    HEIGHT, LENGTH, STATID, VOLUME, VOLUMEBEFORE
    , WEIGHT, WIDTH, WMSPALLETID, CREATEDDATETIME, RECID
    , MODIFIEDDATETIME, MODIFIEDBY, CREATEDBY  
  )
  SELECT HEIGHT, LENGTH, STATID, VOLUME, VOLUMEBEFORE
    , WEIGHT, WIDTH, WMSPALLETID, CREATEDDATETIME, RECID
    , MODIFIEDDATETIME, MODIFIEDBY, CREATEDBY
  FROM LFL_WMSPalletWeightStation T
  WHERE EXISTS (SELECT * FROM #F WHERE #F.RecId = T.RECID)

  COMMIT      -- Test Only
  BEGIN TRAN  -- Test Only

  DELETE T
  FROM LFL_WMSPalletWeightStation T
  WHERE EXISTS (SELECT * FROM #F WHERE #F.RecId = T.RecId)
  OPTION (MAXDOP 8)

  --COMMIT
  ROLLBACK    -- Test Only

  DELETE FROM #R
  WHERE EXISTS (SELECT * FROM #F WHERE #F.RecId = #R.RecId)

  TRUNCATE TABLE #F

  WAITFOR DELAY '00:00:02'
END

-- SELECT * FROM #R

-- ROLLBACK





